<a href="https://colab.research.google.com/github/amandarice97/data-analytics/blob/main/danl-m1-exam-Rice-Amanda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Take-Home Exam

# Part 1 - Beer Markets

Load DataFrame for Part 1:

In [1]:
import pandas as pd
beer_mkts = pd.read_csv('https://bcdanl.github.io/data/beer_markets.csv')
beer_mkts # load dataset

hh        _purchase_desc  quantity          brand  dollar_spent  \
0      2000946      BUD LT BR CN 12P         1      BUD LIGHT          8.14   
1      2003036      BUD LT BR CN 24P         1      BUD LIGHT         17.48   
2      2003036      BUD LT BR CN 24P         2      BUD LIGHT         33.92   
3      2003036      BUD LT BR CN 30P         2      BUD LIGHT         34.74   
4      2003036      BUD LT BR CN 36P         2      BUD LIGHT         40.48   
...        ...                   ...       ...            ...           ...   
73110  9158319  NATURAL LT BR CN 24P         1  NATURAL LIGHT         11.49   
73111  9158319  NATURAL LT BR CN 24P         1  NATURAL LIGHT          9.97   
73112  9158319  NATURAL LT BR CN 24P         1  NATURAL LIGHT          9.98   
73113  9164033  NATURAL LT BR CN 30P         1  NATURAL LIGHT         12.98   
73114  9164155  NATURAL LT BR CN 24P         1  NATURAL LIGHT         13.49   

       beer_floz  price_per_floz container  promo          market  ...  age  \
0          144.0        0.056528       CAN  False  RURAL ILLINOIS  ...  50+   
1          288.0        0.060694       CAN  False         ATLANTA  ...  50+   
2          576.0        0.058889       CAN  False         ATLANTA  ...  50+   
3          720.0        0.048250       CAN  False         ATLANTA  ...  50+   
4          864.0        0.046852       CAN  False         ATLANTA  ...  50+   
...          ...             ...       ...    ...             ...  ...  ...   
73110      288.0        0.039896       CAN   True  RURAL VIRGINIA  ...  50+   
73111      288.0        0.034618       CAN  False  RURAL VIRGINIA  ...  50+   
73112      288.0        0.034653       CAN  False  RURAL VIRGINIA  ...  50+   
73113      360.0        0.036056       CAN  False      SACRAMENTO  ...  50+   
73114      288.0        0.046840       CAN  False    JACKSONVILLE  ...  50+   

      employment   degree                        cow      race microwave  \
0           none     Grad       none/retired/student     white      True   
1           full  College     clerical/sales/service     white      True   
2           full  College     clerical/sales/service     white      True   
3           full  College     clerical/sales/service     white      True   
4           full  College     clerical/sales/service     white      True   
...          ...      ...                        ...       ...       ...   
73110       none       HS       none/retired/student     black      True   
73111       none       HS       none/retired/student     black      True   
73112       none       HS       none/retired/student     black      True   
73113       full  College                       prof  hispanic      True   
73114       full       HS  labor/craft/military/farm     white      True   

      dishwasher  tvcable singlefamilyhome  npeople  
0           True  premium            False        1  
1           True    basic             True        2  
2           True    basic             True        2  
3           True    basic             True        2  
4           True    basic             True        2  
...          ...      ...              ...      ...  
73110       True  premium             True        2  
73111       True  premium             True        2  
73112       True  premium             True        2  
73113       True    basic             True    5plus  
73114       True     none             True        2  

[73115 rows x 24 columns]

- Each observation in beer_mkts is a household-level transaction record for a purchase of beer.

# Variable Description

- hh: an identifier of the household;
- X_purchase_desc: details on the purchased item;
- quantity: the number of items purchased;
- brand: Bud Light, Busch Light, Coors Light, Miller Lite, or Natural Light;
- dollar_spent: total dollar value of purchase;
- beer_floz: total volume of beer, in fluid ounces;
- price_per_floz: price per fl.oz. (i.e., beer spent/beer floz);
- container: the type of container;
- promo: Whether the item was promoted (coupon or otherwise);
- market: Scan-track market (or state if rural);
- demographic data, including gender, marital status, household income, class of work, race, education, age, the size of household, and whether or not the household has a microwave or a dishwasher.

# Question 1

- Find the top 5 beer markets in terms of the number of households that purchased beer.
- Find the top 5 beer markets in terms of the amount of total beer consumption.

*Answer*
- The top 5 beer markets based on the number of hourseholds that purchased beer (total observations) are: Tampa, Miami, San Antonio, Phoenix, and Dallas.
- The top 5 beer markets in terms of total beer consumption are: (1) Tampa (890,418 fl. oz.); (2) Phoenix (675,318 fl. oz.); (3) Miami (632,684 fl. oz.); (4) San Antonio (631,852 fl. oz.); and (5) Chicago (558,878 fl. oz.).

In [7]:
beer_mkts.info() # num. of observations is equal to num. of households (73,115)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73115 entries, 0 to 73114
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   hh                73115 non-null  int64  
 1   _purchase_desc    73115 non-null  object 
 2   quantity          73115 non-null  int64  
 3   brand             73115 non-null  object 
 4   dollar_spent      73115 non-null  float64
 5   beer_floz         73115 non-null  float64
 6   price_per_floz    73115 non-null  float64
 7   container         73115 non-null  object 
 8   promo             73115 non-null  bool   
 9   market            73115 non-null  object 
 10  buyertype         73115 non-null  object 
 11  income            73115 non-null  object 
 12  childrenUnder6    73115 non-null  bool   
 13  children6to17     73115 non-null  bool   
 14  age               73115 non-null  object 
 15  employment        73115 non-null  object 
 16  degree            73115 non-null  object

In [13]:
beer_mkts["quantity"].min() # check to determine whether any households purchased 0 beer, lowest quantity is equal to 1

1

In [8]:
beer_mkts['market'].value_counts().head(5) # top 5 beer mkts based on total number of households (observations = 73,115)

TAMPA          3287
MIAMI          2652
SAN ANTONIO    2651
PHOENIX        2279
DALLAS         2126
Name: market, dtype: int64

In [60]:
market_1 = beer_mkts.groupby(["market"]) # groupby market

In [65]:
market_1["beer_floz"].sum() # sum of fl. oz. beer consumed by market

market
ALBANY           147456.00
ATLANTA          322107.00
BALTIMORE        187116.00
BIRMINGHAM       262252.00
BOSTON           253878.48
                   ...    
SURBURBAN NY     235623.00
SYRACUSE          85504.00
TAMPA            890418.00
URBAN NY         211146.00
WASHINGTON DC    231424.00
Name: beer_floz, Length: 92, dtype: float64

In [64]:
market_1["beer_floz"].sum().sort_values().head(5) # bottom 5 beer markets in terms of consumption

market
RURAL COLORADO          4320.0
RURAL NEW YORK          4752.0
RURAL NEW HAMPSHIRE     7800.0
RURAL OREGON            8106.0
RURAL WYOMING          11088.0
Name: beer_floz, dtype: float64

In [63]:
market_1["beer_floz"].sum().sort_values().tail(5) # top 5 beer markets in terms of consumption

market
CHICAGO        558878.0
SAN ANTONIO    631852.0
MIAMI          632684.0
PHOENIX        675318.0
TAMPA          890418.0
Name: beer_floz, dtype: float64

# Question 2
- For households that purchased BUD LIGHT at least once, what fraction of households did purchase only BUD LIGHT?
- For households that purchased BUSCH LIGHT at least once, what fraction of households did purchase only BUSCH LIGHT?
- For households that purchased COORS LIGHT at least once, what fraction of households did purchase only COORS LIGHT?
- For households that purchased MILLER LITE at least once, what fraction of households did purchase only MILLER LITE?
- For households that purchased NATURAL LIGHT at least once, what fraction of households did purchase only NATURAL LIGHT?
- Which beer brand does have the largest proportion of such loyal consumers?

*Answer*
- BUD LIGHT = 29.53%
- BUSCH LIGHT = 11.86%
- COORS LIGHT = 17.88%
- MILLER LIGHT = 23.47%
- NATURAL LIGHT = 17.26%
- Bud Light has the largest proportion of loyal customers.

In [70]:
beer_mkts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73115 entries, 0 to 73114
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   hh                73115 non-null  int64  
 1   _purchase_desc    73115 non-null  object 
 2   quantity          73115 non-null  int64  
 3   brand             73115 non-null  object 
 4   dollar_spent      73115 non-null  float64
 5   beer_floz         73115 non-null  float64
 6   price_per_floz    73115 non-null  float64
 7   container         73115 non-null  object 
 8   promo             73115 non-null  bool   
 9   market            73115 non-null  object 
 10  buyertype         73115 non-null  object 
 11  income            73115 non-null  object 
 12  childrenUnder6    73115 non-null  bool   
 13  children6to17     73115 non-null  bool   
 14  age               73115 non-null  object 
 15  employment        73115 non-null  object 
 16  degree            73115 non-null  object

In [66]:
beer_mkts['brand'].value_counts() # num. of households (observations) by brand

BUD LIGHT        21592
MILLER LITE      17159
COORS LIGHT      13074
NATURAL LIGHT    12616
BUSCH LIGHT       8674
Name: brand, dtype: int64

In [12]:
BUD_LIGHT = 21592
BUSCH_LIGHT = 8674
COORS_LIGHT = 13074
MILLER_LIGHT = 17159
NATURAL_LIGHT = 12616
TOTAL_HOUSEHOLDS_BY_BRAND = BUD_LIGHT + BUSCH_LIGHT + COORS_LIGHT + MILLER_LIGHT + NATURAL_LIGHT
TOTAL_HOUSEHOLDS_BY_BRAND # check to make sure above values equal total observations in dataframe

73115

In [72]:
BUD_LIGHT = 21592
TOTAL_HOUSEHOLDS = 73115
BUD_LIGHT_FRACTION = (BUD_LIGHT/TOTAL_HOUSEHOLDS)*100
BUD_LIGHT_FRACTION # percent of households that bought only BUD LIGHT

29.53155987143541

In [6]:
BUSCH_LIGHT = 8674
TOTAL_HOUSEHOLDS = 73115
BUSCH_LIGHT_FRACTION = (BUSCH_LIGHT/TOTAL_HOUSEHOLDS)*100
BUSCH_LIGHT_FRACTION # percent of households that bought only BUSCH LIGHT

11.8635027012241

In [4]:
COORS_LIGHT = 13074
TOTAL_HOUSEHOLDS = 73115
COORS_LIGHT_FRACTION = (COORS_LIGHT/TOTAL_HOUSEHOLDS)*100
COORS_LIGHT_FRACTION # percent of households that bought only COORS LIGHT

17.881419681323944

In [5]:
MILLER_LIGHT = 17159
TOTAL_HOUSEHOLDS = 73115
MILLER_LIGHT_FRACTION = (MILLER_LIGHT/TOTAL_HOUSEHOLDS)*100
MILLER_LIGHT_FRACTION # percent of households that bought only MILLER LIGHT

23.46850851398482

In [7]:
NATURAL_LIGHT = 12616
TOTAL_HOUSEHOLDS = 73115
NATURAL_LIGHT_FRACTION = (NATURAL_LIGHT/TOTAL_HOUSEHOLDS)*100
NATURAL_LIGHT_FRACTION # percent of households that bought only NATURAL LIGHT

17.255009232031732

# Part 2 - Search Engine Marketing

Load DataFrame for Part 2

In [1]:
import pandas as pd
paidsearch = pd.read_csv('https://bcdanl.github.io/data/paidsearch.csv')
paidsearch # load dataset

date  dma  treatment_period  search_stays_on       revenue
0       1-Apr-12  500                 0                0  7.671874e+04
1       1-Apr-12  501                 0                1  2.096177e+06
2       1-Apr-12  502                 0                1  3.499385e+04
3       1-Apr-12  503                 0                1  3.419875e+04
4       1-Apr-12  504                 0                1  6.410142e+05
...          ...  ...               ...              ...           ...
23725  22-Jul-12  855                 1                1  6.723426e+04
23726  22-Jul-12  862                 1                1  2.693048e+05
23727  22-Jul-12  866                 1                0  1.015611e+05
23728  22-Jul-12  868                 1                1  3.464549e+04
23729  22-Jul-12  881                 1                1  8.702989e+04

[23730 rows x 5 columns]

# Variable Description
- dma: an identification number of a designated market (DM) area i, defined by Nielsen (e.g., Boston, Los Angeles. This webpage provides the list of DMA names.)
- treatment_period: 0 if date is before May 22, 2012 and 1 after.
- search_stays_on: 1 if the paid-search goes off in dma i, 0 otherwise.
- revenue: eBay’s sales revenue for dma i and date t

# Question 3
Summarize the mean value of revenue for each group of search_stays_on and for each date.

*Answer*

See below for answer.

In [10]:
paidsearch['date'].nunique() # 113 unique values for date

113

In [6]:
paidsearch['date'].value_counts() # count of observations by date

1-Apr-12     210
28-May-12    210
23-Jun-12    210
22-Jun-12    210
21-Jun-12    210
            ... 
5-May-12     210
4-May-12     210
3-May-12     210
2-May-12     210
22-Jul-12    210
Name: date, Length: 113, dtype: int64

In [7]:
search_and_date = paidsearch.groupby(["date", "search_stays_on"]) # group by date then by search_stays_on

In [8]:
search_and_date["revenue"].mean() # mean revenue by date then by search_stays_on

date      search_stays_on
1-Apr-12  0                   93650.675824
          1                  120277.567977
1-Jul-12  0                   84992.376494
          1                  110084.439448
1-Jun-12  0                  106093.754576
                                 ...      
9-Jul-12  1                  145901.554783
9-Jun-12  0                   80096.385494
          1                  105132.224282
9-May-12  0                  113425.081200
          1                  140548.654090
Name: revenue, Length: 226, dtype: float64

# Question 4
Calculate the log difference between mean revenues in each group of search_stays_on. (This is the log of the average revenue in group of search_stays_on == 1 minus the log of the average revenue in group of search_stays_on == 0.)



In [ ]:
# date        the daily mean vale of `revenue`   search_stays_on
# 1-Apr-12    93650.68                           0
# 1-Apr-12    120277.57                          1

# Question 4, Cont.
- The log difference of daily mean revenues between the two group of search_stays_on for date 1-Apr-12 is log(120277.57) - log(93650.68).
- Hint: Below example shows how we can calculate the log of Value using np.log():

In [24]:
import pandas as pd
import numpy as np

# Creating a DataFrame
data = {'Value': [1, 10, 100, 1000, 10000]}
df = pd.DataFrame(data)

# Calculating logarithms
df['Log_natural'] = np.log(df['Value'])
df['Log_natural']

0    0.000000
1    2.302585
2    4.605170
3    6.907755
4    9.210340
Name: Log_natural, dtype: float64

# Question 4, Cont.
*Answer*

See below for answer.

*Note*

I'm unsure how to solve for the difference.

In [2]:
import pandas as pd
import numpy as np

In [27]:
data = search_and_date["revenue"].mean()
df = pd.DataFrame(data)
df['Log_natural'] = np.log(df['revenue'])
df['Log_natural'] # calculate the natural log of mean revenue, grouped by date then by search_stays_on

date      search_stays_on
1-Apr-12  0                  11.447327
          1                  11.697557
1-Jul-12  0                  11.350317
          1                  11.609003
1-Jun-12  0                  11.572078
                               ...    
9-Jul-12  1                  11.890687
9-Jun-12  0                  11.290986
          1                  11.562974
9-May-12  0                  11.638898
          1                  11.853309
Name: Log_natural, Length: 226, dtype: float64

In [1]:
# 1-Apr-12
11.697557 - 11.447327

0.2502300000000002

In [2]:
# 1-Jul-12
11.609003 - 11.350317

0.2586859999999991

In [4]:
# 9-Jun-12
11.562974 - 11.290986

0.27198800000000034

In [5]:
# 9-May-12
11.853309 - 11.638898

0.21441100000000013

# Part 3 - NFL
The following is the DataFrame for Part 3.

In [68]:
import pandas as pd
NFL2023_stuffs = pd.read_csv('https://bcdanl.github.io/data/NFL2023_stuffs.csv')
NFL2023_stuffs # load the dataset

play_id          game_id  drive  week posteam  qtr  down  \
0            1  2023_01_ARI_WAS    NaN     1     NaN    1   NaN   
1           39  2023_01_ARI_WAS    1.0     1     WAS    1   NaN   
2           55  2023_01_ARI_WAS    1.0     1     WAS    1   1.0   
3           77  2023_01_ARI_WAS    1.0     1     WAS    1   2.0   
4          102  2023_01_ARI_WAS    1.0     1     WAS    1   3.0   
...        ...              ...    ...   ...     ...  ...   ...   
49660     4791    2023_22_SF_KC   26.0    22      KC    5   3.0   
49661     4813    2023_22_SF_KC   26.0    22      KC    5   1.0   
49662     4835    2023_22_SF_KC   26.0    22      KC    5   2.0   
49663     4860    2023_22_SF_KC   26.0    22      KC    5   1.0   
49664     4881    2023_22_SF_KC    NaN    22      KC    5   NaN   

       half_seconds_remaining  pass        wp  
0                      1800.0     0  0.546262  
1                      1800.0     0  0.546262  
2                      1800.0     0  0.546262  
3                      1770.0     1  0.539621  
4                      1735.0     0  0.555987  
...                       ...   ...       ...  
49660                   127.0     1  0.648316  
49661                    86.0     0  0.857837  
49662                    50.0     1  0.849875  
49663                     6.0     1  0.871640  
49664                     3.0     0       NaN  

[49665 rows x 10 columns]

In [69]:
NFL2023_stuffs.info() # column num., name, count, data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49665 entries, 0 to 49664
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   play_id                 49665 non-null  int64  
 1   game_id                 49665 non-null  object 
 2   drive                   49098 non-null  float64
 3   week                    49665 non-null  int64  
 4   posteam                 47027 non-null  object 
 5   qtr                     49665 non-null  int64  
 6   down                    41925 non-null  float64
 7   half_seconds_remaining  49660 non-null  float64
 8   pass                    49665 non-null  int64  
 9   wp                      49380 non-null  float64
dtypes: float64(4), int64(4), object(2)
memory usage: 3.8+ MB


- NFL2023_stuffs is the DataFrame that contains information about NFL games in year 2022, in which the unit of observation is a single play for each drive in a NFL game.

# Variable Description
- play_id: Numeric play identifier that when used with game_id and drive provides the unique identifier for a single play
- game_id: Ten digit identifier for NFL game.
- drive: Numeric drive number in the game.
- week: Season week.
- posteam: String abbreviation for the team with possession.
- qtr: Quarter of the game (5 is overtime).
- half_seconds_remaining: Numeric seconds remaining in the half.
- down: The down for the given play.
  - Basically you get four attempts (aka downs) to move the ball 10 yards (by either running with it or passing it).
  - If you make 10 yards then you get another set of four downs.
- pass: Binary indicator if the play was a pass play.
- wp: Estimated winning probability for the posteam given the current situation at the start of the given play.

# Question 5
In DataFrame, NFL2023_stuffs, remove observations for which values of posteam is missing.

*Answer*

In [70]:
NFL2023_stuffs.reset_index(inplace = True) # reset index

In [71]:
NFL2023_stuffs["posteam"].isna() # boolean, True = NaN, False = Otherwise

0         True
1        False
2        False
3        False
4        False
         ...  
49660    False
49661    False
49662    False
49663    False
49664    False
Name: posteam, Length: 49665, dtype: bool

In [72]:
NFL2023_stuffs["posteam"].value_counts(dropna = False) # drop NaN from posteam

NaN    2638
KC     1734
DET    1706
CLE    1620
SF     1603
BUF    1595
BAL    1568
HOU    1560
DAL    1552
TB     1547
GB     1523
PHI    1509
LA     1497
MIA    1455
IND    1450
JAX    1449
NO     1448
LAC    1432
CAR    1432
PIT    1431
ATL    1424
CHI    1415
ARI    1413
NYJ    1411
WAS    1403
NYG    1397
MIN    1386
CIN    1379
DEN    1364
TEN    1351
SEA    1336
NE     1326
LV     1311
Name: posteam, dtype: int64

In [73]:
posteam_drop = NFL2023_stuffs.dropna(subset = ["posteam"])
posteam_drop # drop NaN from posteam

index  play_id          game_id  drive  week posteam  qtr  down  \
1          1       39  2023_01_ARI_WAS    1.0     1     WAS    1   NaN   
2          2       55  2023_01_ARI_WAS    1.0     1     WAS    1   1.0   
3          3       77  2023_01_ARI_WAS    1.0     1     WAS    1   2.0   
4          4      102  2023_01_ARI_WAS    1.0     1     WAS    1   3.0   
5          5      124  2023_01_ARI_WAS    1.0     1     WAS    1   1.0   
...      ...      ...              ...    ...   ...     ...  ...   ...   
49660  49660     4791    2023_22_SF_KC   26.0    22      KC    5   3.0   
49661  49661     4813    2023_22_SF_KC   26.0    22      KC    5   1.0   
49662  49662     4835    2023_22_SF_KC   26.0    22      KC    5   2.0   
49663  49663     4860    2023_22_SF_KC   26.0    22      KC    5   1.0   
49664  49664     4881    2023_22_SF_KC    NaN    22      KC    5   NaN   

       half_seconds_remaining  pass        wp  
1                      1800.0     0  0.546262  
2                      1800.0     0  0.546262  
3                      1770.0     1  0.539621  
4                      1735.0     0  0.555987  
5                      1696.0     1  0.572573  
...                       ...   ...       ...  
49660                   127.0     1  0.648316  
49661                    86.0     0  0.857837  
49662                    50.0     1  0.849875  
49663                     6.0     1  0.871640  
49664                     3.0     0       NaN  

[47027 rows x 11 columns]

In [74]:
posteam_drop.info() # column num., name, count, data type

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47027 entries, 1 to 49664
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   index                   47027 non-null  int64  
 1   play_id                 47027 non-null  int64  
 2   game_id                 47027 non-null  object 
 3   drive                   46873 non-null  float64
 4   week                    47027 non-null  int64  
 5   posteam                 47027 non-null  object 
 6   qtr                     47027 non-null  int64  
 7   down                    41925 non-null  float64
 8   half_seconds_remaining  47022 non-null  float64
 9   pass                    47027 non-null  int64  
 10  wp                      46742 non-null  float64
dtypes: float64(4), int64(5), object(2)
memory usage: 4.3+ MB


# Question 6
Calculate the mean value of pass for each posteam when all the following conditions hold:
- wp is greater than 20% and less than 75%;
- down is less than or equal to 2; and
- half_seconds_remaining is greater than 120.

*Answer*

See below for answer.

In [75]:
wp_greater_than_20 = posteam_drop["wp"] > 0.20
wp_less_than_75 = posteam_drop["wp"] < 0.75
down_less_than_equal_2 = posteam_drop["down"] <= 2
half_seconds_greater_than_120 = posteam_drop["half_seconds_remaining"] > 120
posteam_drop[ wp_greater_than_20 & wp_less_than_75 & down_less_than_equal_2 & half_seconds_greater_than_120 ] # filter by more than 1 condition

index  play_id          game_id  drive  week posteam  qtr  down  \
2          2       55  2023_01_ARI_WAS    1.0     1     WAS    1   1.0   
3          3       77  2023_01_ARI_WAS    1.0     1     WAS    1   2.0   
5          5      124  2023_01_ARI_WAS    1.0     1     WAS    1   1.0   
6          6      147  2023_01_ARI_WAS    1.0     1     WAS    1   2.0   
7          7      172  2023_01_ARI_WAS    1.0     1     WAS    1   1.0   
...      ...      ...              ...    ...   ...     ...  ...   ...   
49650  49650     4583    2023_22_SF_KC   26.0    22      KC    5   2.0   
49654  49654     4659    2023_22_SF_KC   26.0    22      KC    5   1.0   
49655  49655     4684    2023_22_SF_KC   26.0    22      KC    5   2.0   
49657  49657     4734    2023_22_SF_KC   26.0    22      KC    5   1.0   
49659  49659     4759    2023_22_SF_KC   26.0    22      KC    5   2.0   

       half_seconds_remaining  pass        wp  
2                      1800.0     0  0.546262  
3                      1770.0     1  0.539621  
5                      1696.0     1  0.572573  
6                      1692.0     1  0.554537  
7                      1654.0     1  0.584447  
...                       ...   ...       ...  
49650                   410.0     1  0.464061  
49654                   328.0     1  0.599889  
49655                   286.0     1  0.464849  
49657                   213.0     1  0.654356  
49659                   168.0     1  0.560584  

[15137 rows x 11 columns]

In [76]:
pass_mean = posteam_drop.groupby(["posteam"]) # groupby posteam

In [77]:
pass_mean["pass"].mean() # calculate pass mean by posteam, factoring in filtering done above

posteam
ARI    0.479122
ATL    0.441011
BAL    0.462372
BUF    0.484013
CAR    0.506285
CHI    0.455830
CIN    0.528644
CLE    0.485185
DAL    0.518686
DEN    0.470674
DET    0.464244
GB     0.476691
HOU    0.487179
IND    0.473103
JAX    0.516218
KC     0.540369
LA     0.480962
LAC    0.527933
LV     0.480549
MIA    0.469416
MIN    0.541126
NE     0.487934
NO     0.468232
NYG    0.501790
NYJ    0.518072
PHI    0.479125
PIT    0.449336
SEA    0.506737
SF     0.431691
TB     0.500970
TEN    0.455959
WAS    0.553100
Name: pass, dtype: float64

# Question 7
- Consider the following DataFrame, NFL2023_epa:

In [78]:
import pandas as pd
NFL2023_epa = pd.read_csv('https://bcdanl.github.io/data/NFL2023_epa.csv')
NFL2023_epa # load dataset

play_id          game_id  drive posteam   receiver     passer       epa
0           39  2023_01_ARI_WAS    1.0     WAS        NaN        NaN  0.000000
1           55  2023_01_ARI_WAS    1.0     WAS        NaN        NaN -0.336103
2           77  2023_01_ARI_WAS    1.0     WAS   J.Dotson   S.Howell  0.703308
3          102  2023_01_ARI_WAS    1.0     WAS        NaN        NaN  0.469799
4          124  2023_01_ARI_WAS    1.0     WAS   L.Thomas   S.Howell -0.521544
...        ...              ...    ...     ...        ...        ...       ...
47022     4791    2023_22_SF_KC   26.0      KC        NaN  P.Mahomes  1.728891
47023     4813    2023_22_SF_KC   26.0      KC        NaN        NaN -0.330699
47024     4835    2023_22_SF_KC   26.0      KC    T.Kelce  P.Mahomes -0.637115
47025     4860    2023_22_SF_KC   26.0      KC  M.Hardman  P.Mahomes  3.102806
47026     4881    2023_22_SF_KC    NaN      KC        NaN        NaN       NaN

[47027 rows x 7 columns]

# Variable Description
- play_id: Numeric play identifier that when used with game_id and drive provides the unique identifier for a single play
- game_id: Ten digit identifier for NFL game.
- drive: Numeric drive number in the game.
- posteam: String abbreviation for the team with possession.
- passer: Name of the player who passed a ball to a receiver by initially - taking a three-step drop and backpedaling into the pocket to make a pass. (Mostly, they are quarterbacks)
- receiver: Name of the receiver.
- epa: Expected points added (EPA) by the posteam for the given play.

In [79]:
NFL2023_epa.info() # column num., name, count, data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47027 entries, 0 to 47026
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   play_id   47027 non-null  int64  
 1   game_id   47027 non-null  object 
 2   drive     46873 non-null  float64
 3   posteam   47027 non-null  object 
 4   receiver  19373 non-null  object 
 5   passer    22979 non-null  object 
 6   epa       46742 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.5+ MB


# Question 7, Cont.
- Create the DataFrame, NFL2023_stuffs_EPA, that includes
  - All the variables in the DataFrame, NFL2023_stuffs;
  - The variables, passer, receiver, and epa, from the DataFrame, NFL2023_epa. by joining the two DataFrames.
- In the resulting DataFrame, NFL2023_stuffs_EPA, remove observations with NA in passer.

*Answer*

See below for answer.

In [86]:
import pandas as pd
NFL2023_stuffs = pd.read_csv('https://bcdanl.github.io/data/NFL2023_stuffs.csv')
NFL2023_epa = pd.read_csv('https://bcdanl.github.io/data/NFL2023_epa.csv')

In [87]:
NFL2023_stuffs.columns # list columns in NFL2023_stuffs DataFrame

Index(['play_id', 'game_id', 'drive', 'week', 'posteam', 'qtr', 'down',
       'half_seconds_remaining', 'pass', 'wp'],
      dtype='object')

In [98]:
NFL2023_epa.columns # list columns in NFL2023_epa DataFrame

Index(['play_id', 'game_id', 'drive', 'posteam', 'receiver', 'passer', 'epa'], dtype='object')

In [103]:
stuffs_epa = (
    NFL2023_stuffs
    .merge(NFL2023_epa)
)
stuffs_epa # merge DataFrames

play_id          game_id  drive  week posteam  qtr  down  \
0           39  2023_01_ARI_WAS    1.0     1     WAS    1   NaN   
1           55  2023_01_ARI_WAS    1.0     1     WAS    1   1.0   
2           77  2023_01_ARI_WAS    1.0     1     WAS    1   2.0   
3          102  2023_01_ARI_WAS    1.0     1     WAS    1   3.0   
4          124  2023_01_ARI_WAS    1.0     1     WAS    1   1.0   
...        ...              ...    ...   ...     ...  ...   ...   
47022     4791    2023_22_SF_KC   26.0    22      KC    5   3.0   
47023     4813    2023_22_SF_KC   26.0    22      KC    5   1.0   
47024     4835    2023_22_SF_KC   26.0    22      KC    5   2.0   
47025     4860    2023_22_SF_KC   26.0    22      KC    5   1.0   
47026     4881    2023_22_SF_KC    NaN    22      KC    5   NaN   

       half_seconds_remaining  pass        wp   receiver     passer       epa  
0                      1800.0     0  0.546262        NaN        NaN  0.000000  
1                      1800.0     0  0.546262        NaN        NaN -0.336103  
2                      1770.0     1  0.539621   J.Dotson   S.Howell  0.703308  
3                      1735.0     0  0.555987        NaN        NaN  0.469799  
4                      1696.0     1  0.572573   L.Thomas   S.Howell -0.521544  
...                       ...   ...       ...        ...        ...       ...  
47022                   127.0     1  0.648316        NaN  P.Mahomes  1.728891  
47023                    86.0     0  0.857837        NaN        NaN -0.330699  
47024                    50.0     1  0.849875    T.Kelce  P.Mahomes -0.637115  
47025                     6.0     1  0.871640  M.Hardman  P.Mahomes  3.102806  
47026                     3.0     0       NaN        NaN        NaN       NaN  

[47027 rows x 13 columns]

In [104]:
passer_drop = stuffs_epa.dropna(subset = ["passer"])
passer_drop # drop NaN from passer

play_id          game_id  drive  week posteam  qtr  down  \
2           77  2023_01_ARI_WAS    1.0     1     WAS    1   2.0   
4          124  2023_01_ARI_WAS    1.0     1     WAS    1   1.0   
5          147  2023_01_ARI_WAS    1.0     1     WAS    1   2.0   
6          172  2023_01_ARI_WAS    1.0     1     WAS    1   1.0   
7          197  2023_01_ARI_WAS    1.0     1     WAS    1   2.0   
...        ...              ...    ...   ...     ...  ...   ...   
47020     4734    2023_22_SF_KC   26.0    22      KC    5   1.0   
47021     4759    2023_22_SF_KC   26.0    22      KC    5   2.0   
47022     4791    2023_22_SF_KC   26.0    22      KC    5   3.0   
47024     4835    2023_22_SF_KC   26.0    22      KC    5   2.0   
47025     4860    2023_22_SF_KC   26.0    22      KC    5   1.0   

       half_seconds_remaining  pass        wp   receiver     passer       epa  
2                      1770.0     1  0.539621   J.Dotson   S.Howell  0.703308  
4                      1696.0     1  0.572573   L.Thomas   S.Howell -0.521544  
5                      1692.0     1  0.554537   J.Dotson   S.Howell  1.173155  
6                      1654.0     1  0.584447   C.Samuel   S.Howell -0.515452  
7                      1616.0     1  0.566532   L.Thomas   S.Howell -0.872005  
...                       ...   ...       ...        ...        ...       ...  
47020                   213.0     1  0.654356  I.Pacheco  P.Mahomes -0.682791  
47021                   168.0     1  0.560584  I.Pacheco  P.Mahomes  0.552538  
47022                   127.0     1  0.648316        NaN  P.Mahomes  1.728891  
47024                    50.0     1  0.849875    T.Kelce  P.Mahomes -0.637115  
47025                     6.0     1  0.871640  M.Hardman  P.Mahomes  3.102806  

[22979 rows x 13 columns]